apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustserver.fullname" . }}-secrets
  labels:
    {{- include "rustserver.labels" . | nindent 4 }}
stringData:
{{- range $name, $value := .Values.secrets }}
  {{ $name }}: {{ $value }}
{{- end }}